const CartActionTypes = {
  TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN',
  CLOSE_CART_DRAWER: 'CLOSE_CART_DRAWER',
  ADD_ITEM: 'ADD_ITEM',
  DELETE_ITEM: 'DELETE_ITEM',
  INCREASE_ITEMS_COUNT: 'INCREASE_ITEMS_COUNT',
  DECREASE_ITEMS_COUNT: 'ECREASE_ITEMS_COUNT',
};

export default CartActionTypes;
